### ISSUE TITLE
README wrong shown output for compliment

### ISSUE THREAD

**Issue by geoidesic** [edmofro/set-manipulator#1]
Hi,

I think the shown value for your compliment example should be `[1,2]` not `[1]`

**Comment by edmofro** [comment]
Good catch, thanks @geoidesic :-)

Fixed in https://github.com/edmofro/set-manipulator/commit/bf87c06306b5d8ba3e97fd9410a7a5eeee26da23

Haven't published a new version to npm as this is a doc change only
